export const LOAD_DETAIL_REQUEST = "LOAD_DETAIL_REQUEST";
export const LOAD_DETAIL_SUCCESS = "LOAD_DETAIL_SUCCESS";
export const LOAD_DETAIL_ERROR = "LOAD_DETAIL_ERROR";

export const GET_TRAILER_REQUEST = "GET_TRAILER_REQUEST";
export const GET_TRAILER_SUCCESS = "GET_TRAILER_SUCCESS";
export const GET_TRAILER_ERROR = "GET_TRAILER_ERROR";

export const GET_REC_REQUEST = "GET_REC_REQUEST";
export const GET_REC_SUCCESS = "GET_REC_SUCCESS";
export const GET_REC_ERROR = "GET_REC_ERROR";